import type { Booking, BookingAttempt, ReservationRequest, User } from "./types";

/**
 * Seed data for the demo experience. In production these rows live in Supabase;
 * here they let the whole product be explored without a backend.
 */

function daysFromNow(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(
    d.getDate(),
  ).padStart(2, "0")}`;
}

function minsAgo(n: number): string {
  return new Date(Date.now() - n * 60_000).toISOString();
}
function minsAhead(n: number): string {
  return new Date(Date.now() + n * 60_000).toISOString();
}

export const SEED_USER: User = {
  id: "usr_demo",
  name: "Alex Rivera",
  email: "alex@example.com",
  plan: "free",
  default_city: "New York",
  default_party_size: 2,
  created_at: minsAgo(60 * 24 * 9),
  updated_at: minsAgo(30),
};

const base = {
  user_id: "usr_demo",
  seating_preference: "any" as const,
  priority: "normal" as const,
  credit_required: false,
  notes: "",
};

export const SEED_REQUESTS: ReservationRequest[] = [
  {
    ...base,
    id: "req_donangie",
    restaurant_name: "Don Angie",
    platform: "resy",
    city: "New York",
    neighborhood: "West Village",
    party_size: 2,
    date_start: daysFromNow(3),
    date_end: daysFromNow(5),
    time_start: "18:30",
    time_end: "21:30",
    flexibility_level: "flexible",
    seating_preference: "any",
    priority: "high",
    status: "active",
    auto_book_enabled: true,
    expires_at: daysFromNow(5) + "T23:59:00.000Z",
    last_checked_at: minsAgo(2),
    next_check_at: minsAhead(1),
    created_at: minsAgo(60 * 20),
    updated_at: minsAgo(2),
    notes: "Anniversary dinner — would love a banquette.",
  },
  {
    ...base,
    id: "req_tatiana",
    restaurant_name: "Tatiana",
    platform: "resy",
    city: "New York",
    neighborhood: "Lincoln Center",
    party_size: 2,
    date_start: daysFromNow(2),
    date_end: daysFromNow(6),
    time_start: "18:00",
    time_end: "22:00",
    flexibility_level: "very_flexible",
    priority: "normal",
    status: "active",
    auto_book_enabled: true,
    expires_at: daysFromNow(6) + "T23:59:00.000Z",
    last_checked_at: minsAgo(4),
    next_check_at: minsAhead(1),
    created_at: minsAgo(60 * 30),
    updated_at: minsAgo(4),
  },
  {
    ...base,
    id: "req_cote",
    restaurant_name: "Cote",
    platform: "opentable",
    city: "New York",
    neighborhood: "Flatiron",
    party_size: 4,
    date_start: daysFromNow(5),
    date_end: daysFromNow(5),
    time_start: "18:00",
    time_end: "21:00",
    flexibility_level: "flexible",
    priority: "normal",
    status: "draft",
    auto_book_enabled: false,
    expires_at: daysFromNow(5) + "T23:59:00.000Z",
    last_checked_at: null,
    next_check_at: null,
    created_at: minsAgo(60 * 5),
    updated_at: minsAgo(60 * 5),
    notes: "Korean steakhouse night with friends.",
  },
  {
    ...base,
    id: "req_lilia",
    restaurant_name: "Lilia",
    platform: "resy",
    city: "New York",
    neighborhood: "Williamsburg",
    party_size: 2,
    date_start: daysFromNow(6),
    date_end: daysFromNow(7),
    time_start: "19:30",
    time_end: "21:30",
    flexibility_level: "flexible",
    priority: "normal",
    status: "draft",
    auto_book_enabled: false,
    expires_at: null,
    last_checked_at: null,
    next_check_at: null,
    created_at: minsAgo(60 * 2),
    updated_at: minsAgo(60 * 2),
  },
  {
    ...base,
    id: "req_carbone",
    restaurant_name: "Carbone",
    platform: "resy",
    city: "New York",
    neighborhood: "Greenwich Village",
    party_size: 2,
    date_start: daysFromNow(1),
    date_end: daysFromNow(1),
    time_start: "20:00",
    time_end: "22:00",
    flexibility_level: "strict",
    priority: "high",
    status: "booked",
    auto_book_enabled: false,
    expires_at: daysFromNow(1) + "T23:59:00.000Z",
    last_checked_at: minsAgo(18),
    next_check_at: null,
    created_at: minsAgo(60 * 30),
    updated_at: minsAgo(18),
  },
  {
    ...base,
    id: "req_rezdora",
    restaurant_name: "Rezdora",
    platform: "resy",
    city: "New York",
    neighborhood: "Flatiron",
    party_size: 3,
    date_start: daysFromNow(-5),
    date_end: daysFromNow(-5),
    time_start: "18:00",
    time_end: "20:00",
    flexibility_level: "strict",
    priority: "normal",
    status: "expired",
    auto_book_enabled: false,
    expires_at: daysFromNow(-5) + "T23:59:00.000Z",
    last_checked_at: minsAgo(60 * 120),
    next_check_at: null,
    created_at: minsAgo(60 * 200),
    updated_at: minsAgo(60 * 120),
  },
];

export const SEED_ATTEMPTS: BookingAttempt[] = [
  {
    id: "att_1",
    reservation_request_id: "req_donangie",
    platform: "resy",
    status: "checked_no_match",
    message: "Checked Resy. No table yet.",
    checked_at: minsAgo(12),
    created_at: minsAgo(12),
  },
  {
    id: "att_2",
    reservation_request_id: "req_donangie",
    platform: "resy",
    status: "checked_no_match",
    message: "Checked Resy. No table yet.",
    checked_at: minsAgo(2),
    created_at: minsAgo(2),
  },
  {
    id: "att_3",
    reservation_request_id: "req_tatiana",
    platform: "resy",
    status: "checked_no_match",
    message: "Checked Resy. No table yet.",
    checked_at: minsAgo(4),
    created_at: minsAgo(4),
  },
  {
    id: "att_carbone_1",
    reservation_request_id: "req_carbone",
    platform: "resy",
    status: "checked_no_match",
    message: "Checked Resy. No table yet.",
    checked_at: minsAgo(40),
    created_at: minsAgo(40),
  },
  {
    id: "att_carbone_2",
    reservation_request_id: "req_carbone",
    platform: "resy",
    status: "match_found",
    message: "Found a table — we sent your one-tap booking link.",
    checked_at: minsAgo(18),
    created_at: minsAgo(18),
  },
];

export const SEED_BOOKINGS: Booking[] = [
  {
    id: "found_carbone",
    user_id: "usr_demo",
    reservation_request_id: "req_carbone",
    restaurant_name: "Carbone",
    platform: "resy",
    date: daysFromNow(1),
    time: "20:00",
    party_size: 2,
    book_url: "https://resy.com/cities/ny/venues/carbone?date=" + daysFromNow(1) + "&seats=2",
    status: "found",
    found_at: minsAgo(18),
    created_at: minsAgo(18),
    updated_at: minsAgo(18),
  },
];
