import type {
  Booking,
  BookingAttempt,
  ConnectedAccount,
  CreditTransaction,
  ReservationRequest,
  User,
} from "./types";

/**
 * Seed data for the demo experience. In production these rows live in D1;
 * here they let the whole product be explored without a backend.
 */

function daysFromNow(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(
    d.getDate(),
  ).padStart(2, "0")}`;
}

function minsAgo(n: number): string {
  return new Date(Date.now() - n * 60_000).toISOString();
}
function minsAhead(n: number): string {
  return new Date(Date.now() + n * 60_000).toISOString();
}

export const SEED_USER: User = {
  id: "usr_demo",
  name: "Alex Rivera",
  email: "alex@example.com",
  credit_balance: 4,
  free_credit_granted: true,
  free_credit_used: true,
  default_city: "New York",
  default_party_size: 2,
  created_at: minsAgo(60 * 24 * 9),
  updated_at: minsAgo(30),
};

export const SEED_CONNECTIONS: ConnectedAccount[] = [
  {
    id: "con_resy",
    user_id: "usr_demo",
    provider: "resy",
    status: "connected",
    account_label: "alex@example.com",
    last_checked_at: minsAgo(8),
    created_at: minsAgo(60 * 24 * 9),
    updated_at: minsAgo(8),
  },
  {
    id: "con_ot",
    user_id: "usr_demo",
    provider: "opentable",
    status: "disconnected",
    account_label: null,
    last_checked_at: null,
    created_at: minsAgo(60 * 24 * 9),
    updated_at: minsAgo(60 * 24 * 9),
  },
];

const base = {
  user_id: "usr_demo",
  seating_preference: "any" as const,
  priority: "normal" as const,
  credit_required: true,
  notes: "",
};

export const SEED_REQUESTS: ReservationRequest[] = [
  {
    ...base,
    id: "req_donangie",
    restaurant_name: "Don Angie",
    platform: "resy",
    city: "New York",
    neighborhood: "West Village",
    party_size: 2,
    date_start: daysFromNow(3),
    date_end: daysFromNow(3),
    time_start: "19:00",
    time_end: "21:00",
    flexibility_level: "flexible",
    seating_preference: "any",
    priority: "high",
    status: "active",
    auto_book_enabled: true,
    expires_at: daysFromNow(3) + "T23:59:00.000Z",
    last_checked_at: minsAgo(2),
    next_check_at: minsAhead(1),
    created_at: minsAgo(60 * 20),
    updated_at: minsAgo(2),
    notes: "Anniversary dinner — would love a banquette.",
  },
  {
    ...base,
    id: "req_tatiana",
    restaurant_name: "Tatiana",
    platform: "resy",
    city: "New York",
    neighborhood: "Lincoln Center",
    party_size: 2,
    date_start: daysFromNow(2),
    date_end: daysFromNow(6),
    time_start: "18:30",
    time_end: "21:30",
    flexibility_level: "very_flexible",
    priority: "normal",
    status: "active",
    auto_book_enabled: true,
    expires_at: daysFromNow(6) + "T23:59:00.000Z",
    last_checked_at: minsAgo(4),
    next_check_at: minsAhead(1),
    created_at: minsAgo(60 * 30),
    updated_at: minsAgo(4),
  },
  {
    ...base,
    id: "req_cote",
    restaurant_name: "Cote",
    platform: "opentable",
    city: "New York",
    neighborhood: "Flatiron",
    party_size: 4,
    date_start: daysFromNow(5),
    date_end: daysFromNow(5),
    time_start: "18:00",
    time_end: "21:00",
    flexibility_level: "strict",
    priority: "normal",
    status: "needs_connection",
    auto_book_enabled: false,
    expires_at: daysFromNow(5) + "T23:59:00.000Z",
    last_checked_at: null,
    next_check_at: null,
    created_at: minsAgo(60 * 5),
    updated_at: minsAgo(60 * 5),
    notes: "Korean steakhouse night with friends.",
  },
  {
    ...base,
    id: "req_lilia",
    restaurant_name: "Lilia",
    platform: "resy",
    city: "New York",
    neighborhood: "Williamsburg",
    party_size: 2,
    date_start: daysFromNow(6),
    date_end: daysFromNow(7),
    time_start: "19:30",
    time_end: "21:30",
    flexibility_level: "flexible",
    priority: "normal",
    status: "draft",
    auto_book_enabled: false,
    expires_at: null,
    last_checked_at: null,
    next_check_at: null,
    created_at: minsAgo(60 * 2),
    updated_at: minsAgo(60 * 2),
  },
  {
    ...base,
    id: "req_carbone",
    restaurant_name: "Carbone",
    platform: "resy",
    city: "New York",
    neighborhood: "Greenwich Village",
    party_size: 2,
    date_start: daysFromNow(-2),
    date_end: daysFromNow(-2),
    time_start: "20:00",
    time_end: "22:00",
    flexibility_level: "strict",
    priority: "high",
    status: "booked",
    auto_book_enabled: false,
    expires_at: daysFromNow(-2) + "T23:59:00.000Z",
    last_checked_at: minsAgo(60 * 48),
    next_check_at: null,
    created_at: minsAgo(60 * 72),
    updated_at: minsAgo(60 * 48),
  },
  {
    ...base,
    id: "req_rezdora",
    restaurant_name: "Rezdora",
    platform: "resy",
    city: "New York",
    neighborhood: "Flatiron",
    party_size: 3,
    date_start: daysFromNow(-5),
    date_end: daysFromNow(-5),
    time_start: "18:00",
    time_end: "20:00",
    flexibility_level: "strict",
    priority: "normal",
    status: "expired",
    auto_book_enabled: false,
    expires_at: daysFromNow(-5) + "T23:59:00.000Z",
    last_checked_at: minsAgo(60 * 120),
    next_check_at: null,
    created_at: minsAgo(60 * 200),
    updated_at: minsAgo(60 * 120),
  },
];

export const SEED_ATTEMPTS: BookingAttempt[] = [
  {
    id: "att_1",
    reservation_request_id: "req_donangie",
    platform: "resy",
    status: "checked_no_match",
    message: "Checked Resy. No matching table.",
    checked_at: minsAgo(12),
    created_at: minsAgo(12),
  },
  {
    id: "att_2",
    reservation_request_id: "req_donangie",
    platform: "resy",
    status: "checked_no_match",
    message: "Checked Resy. No matching table.",
    checked_at: minsAgo(2),
    created_at: minsAgo(2),
  },
  {
    id: "att_3",
    reservation_request_id: "req_tatiana",
    platform: "resy",
    status: "checked_no_match",
    message: "Checked Resy. No matching table.",
    checked_at: minsAgo(4),
    created_at: minsAgo(4),
  },
  {
    id: "att_carbone_1",
    reservation_request_id: "req_carbone",
    platform: "resy",
    status: "match_found",
    message: "Found matching table.",
    checked_at: minsAgo(60 * 48 + 3),
    created_at: minsAgo(60 * 48 + 3),
  },
  {
    id: "att_carbone_2",
    reservation_request_id: "req_carbone",
    platform: "resy",
    status: "booking_succeeded",
    message: "Booking succeeded. Free credit used — your first booking was on us.",
    checked_at: minsAgo(60 * 48),
    created_at: minsAgo(60 * 48),
  },
];

export const SEED_BOOKINGS: Booking[] = [
  {
    id: "bkg_carbone",
    user_id: "usr_demo",
    reservation_request_id: "req_carbone",
    restaurant_name: "Carbone",
    platform: "resy",
    date: daysFromNow(-2),
    time: "20:00",
    party_size: 2,
    confirmation_number: "RSY-4820193",
    status: "confirmed",
    credit_used: false,
    booked_at: minsAgo(60 * 48),
    created_at: minsAgo(60 * 48),
    updated_at: minsAgo(60 * 48),
  },
];

export const SEED_TRANSACTIONS: CreditTransaction[] = [
  {
    id: "ctx_signup",
    user_id: "usr_demo",
    type: "signup_bonus",
    amount: 1,
    reason: "Welcome — your first booking is free",
    booking_id: null,
    created_at: minsAgo(60 * 24 * 9),
  },
  {
    id: "ctx_purchase",
    user_id: "usr_demo",
    type: "purchase",
    amount: 3,
    reason: "Credit package — Taste",
    booking_id: null,
    created_at: minsAgo(60 * 24 * 5),
  },
  {
    id: "ctx_carbone",
    user_id: "usr_demo",
    type: "booking_success",
    amount: 0,
    reason: "First successful booking at Carbone — free",
    booking_id: "bkg_carbone",
    created_at: minsAgo(60 * 48),
  },
];
